from analysis.algebra.fold import fold_gcd, fold_lcm, fold_lcm_span, fold_profile, passes_kgv_gate, substance_covers_batch
from analysis.algebra.fusion import fuse_weighted_scores, fuse_with_zero_reason, log_jaccard_basis_blend
from analysis.algebra.gates import (
    BasisGateResult,
    domain_scalar_gate,
    passes_document_relevance,
    prime_sets_disjoint,
    profile_pair_gate,
    profile_symmetry_guard,
    substance_pair_gate,
)
from analysis.algebra.i_metrics import i_ratio_distance, i_ratio_similarity
from analysis.algebra.log_profile import (
    compare_profiles_sparse,
    log_gcd_similarity,
    log_jaccard_primes,
    prime_entropy,
    profile_log_norm,
)
from analysis.algebra.minhash import minhash_band_distance, prime_minhash
from analysis.algebra.multiset import anagram_class_key, perm_compatible, substance_quotient_ingredients
from analysis.algebra.offset import classify_structural_offset, structural_twin_key
from analysis.algebra.sparse_counter import (
    counter_cosine,
    counter_cosine_guarded,
    counter_jaccard,
    counter_jaccard_guarded,
    counter_overlap,
    weighted_channel_score,
)
from analysis.algebra.substance_kernel import (
    compare_substances,
    coupled_point_distance,
    coupled_point_similarity,
    empty_transition_fields,
    substance_covers,
    substance_ggt_kgv_distance,
    substance_ggt_kgv_similarity,
    substance_remainder,
    substance_transition_fields,
    substance_transition_similarity,
    transition_fields,
)
from analysis.algebra.tier_fusion import fuse_tier_scores
from analysis.algebra.typed_bridge import (
    document_di_sketch,
    document_ni_sketch,
    document_typed_sketch,
    typed_sketch_jaccard,
)
from analysis.algebra.window_fold import (
    ExponentWindow,
    compare_windows_pair,
    exponent_window_to_substance,
    fold_window_from_series,
    fold_window_from_token_exponents,
    window_similarity,
)

__all__ = [
    "BasisGateResult",
    "ExponentWindow",
    "anagram_class_key",
    "classify_structural_offset",
    "compare_profiles_sparse",
    "compare_substances",
    "compare_windows_pair",
    "counter_cosine",
    "counter_cosine_guarded",
    "counter_jaccard",
    "counter_jaccard_guarded",
    "counter_overlap",
    "coupled_point_distance",
    "coupled_point_similarity",
    "document_di_sketch",
    "document_ni_sketch",
    "document_typed_sketch",
    "domain_scalar_gate",
    "empty_transition_fields",
    "exponent_window_to_substance",
    "fold_gcd",
    "fold_lcm",
    "fold_lcm_span",
    "fold_profile",
    "fold_window_from_series",
    "fold_window_from_token_exponents",
    "fuse_tier_scores",
    "fuse_weighted_scores",
    "fuse_with_zero_reason",
    "i_ratio_distance",
    "i_ratio_similarity",
    "log_gcd_similarity",
    "log_jaccard_basis_blend",
    "log_jaccard_primes",
    "minhash_band_distance",
    "passes_document_relevance",
    "passes_kgv_gate",
    "perm_compatible",
    "prime_entropy",
    "prime_minhash",
    "prime_sets_disjoint",
    "profile_log_norm",
    "profile_pair_gate",
    "profile_symmetry_guard",
    "structural_twin_key",
    "substance_covers",
    "substance_covers_batch",
    "substance_ggt_kgv_distance",
    "substance_ggt_kgv_similarity",
    "substance_pair_gate",
    "substance_quotient_ingredients",
    "substance_remainder",
    "substance_transition_fields",
    "substance_transition_similarity",
    "transition_fields",
    "typed_sketch_jaccard",
    "weighted_channel_score",
    "window_similarity",
]
