"""AlphabetProfile — User: 'Schriftsatz' / welches Alpha-Profil."""

from __future__ import annotations

from enum import Enum


class AlphabetProfile(str, Enum):
    OG = "og"
    ROMAN = "roman"
    GREEK = "greek"
    CYRILLIC = "cyrillic"
    ARABIC = "arabic"
    HEBREW = "hebrew"
    DEVANAGARI = "devanagari"
    THAI = "thai"
    HANGUL = "hangul"
    HIRAGANA = "hiragana"
    KATAKANA = "katakana"
    ARMENIAN = "armenian"
    GEORGIAN = "georgian"
    GURMUKHI = "gurmukhi"
    TAMIL = "tamil"
    AMHARIC = "amharic"
    COPTIC = "coptic"
    RUNIC = "runic"
    PHOENICIAN = "phoenician"
    UGARITIC = "ugaritic"
    OGHAM = "ogham"
    GLAGOLITIC = "glagolitic"
    GOTHIC = "gothic"
    MONGOLIAN = "mongolian"
    THAANA = "thaana"
    TIFINAGH = "tifinagh"
    BENGALI = "bengali"
    TELUGU = "telugu"
    JAVANESE = "javanese"
    OLD_PERSIAN = "old_persian"
    AESTHETIC_HIEROGLYPHS = "aesthetic_hieroglyphs"
    OLD_ITALIC = "old_italic"
    OLD_TURKIC = "old_turkic"
