import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from web.app import app


class TestStaticUi(unittest.TestCase):
    def test_app_js_has_valid_if_syntax(self):
        js = (ROOT / "web" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertNotIn("if data.", js)
        self.assertIn("if (data.skipped)", js)
        self.assertIn("history.pushState", js)
        self.assertIn("popstate", js)
        self.assertIn("checkServerHealth", js)
        self.assertIn("/api/health", js)
        self.assertIn("function activateTab", js)
        self.assertIn("initGpmEditor", js)
        self.assertIn("FileReader", js)
        self.assertIn("loadGpmIntoEditor", js)
        self.assertIn("runGpmRead", js)
        self.assertIn("ingestGpmFile", js)
        self.assertIn("gpm-load-gpm-btn", js)
        self.assertIn("gpm-gpm-file", js)
        self.assertIn("renderReconstruction", js)
        self.assertIn("runSizeCompare", js)
        self.assertIn("/api/size/encode-word", js)
        self.assertIn("compare-result", js)
        self.assertIn("compare-notes", js)
        self.assertIn("toggleGpmSearchFields", js)
        self.assertIn("renderSiStorageStat", js)
        self.assertIn("si_storage", js)
        self.assertIn("normalized: w.normalized", js)
        self.assertIn("gpm-search-query2", js)
        self.assertIn("mode === 'lcm'", js)
        self.assertIn("'deckt kgV ab'", js)
        self.assertIn("covers_lcm", js)
        self.assertIn("compare-lcm-card", js)
        self.assertIn("compare-match-grid", js)
        self.assertIn("/api/diff", js)
        self.assertIn("wortpaar-form", js)
        self.assertIn("refreshPairModeUi", js)
        self.assertIn("LEGACY_TAB_HASH", js)
        self.assertIn("initDropzone", js)
        self.assertIn("refreshCipherPanel", js)
        self.assertIn("diff-rest-card", js)
        self.assertIn("/api/i-curve", js)
        self.assertIn("ikurve-form", js)
        self.assertIn("ikurve-gpm-drop", js)
        self.assertIn("loadIcurveSideGpmFile", js)
        self.assertIn("gpmPlainBase64", js)
        self.assertIn("sparklineExtent", js)
        self.assertIn("chartScale", js)
        self.assertIn("renderPairedSparklines", js)
        self.assertIn("ikurve-sparkline-scroll", js)
        self.assertIn("ikurve-chart-pair", js)
        self.assertIn("renderDtwFailedWarning", js)
        self.assertIn("ikurve-charts", js)
        self.assertIn("mergeSpectroMatches", js)
        self.assertIn("expandSpectroMatches", js)
        self.assertIn("tokenSpanToCharRange", js)
        self.assertIn("normalizeTextNfc", js)
        self.assertIn("syncEditorNormalizedText", js)
        self.assertIn("replace(/\\r\\n/g", js)
        self.assertIn("abortIcurveSpectroscope", js)
        self.assertIn("abortIcurveSpectroHttp", js)
        self.assertIn("ikurveSpectroGeneration", js)
        self.assertIn("abortGpmSpectroscope", js)
        self.assertIn("signal: controller.signal", js)
        self.assertIn("spectro-crossfire", js)
        self.assertIn("/api/spectroscope", js)
        self.assertNotIn("renderHierarchyBlock", js)
        self.assertIn("renderMetaGenomeCard", js)
        self.assertIn("renderPlagiarismAssessment", js)
        self.assertIn("updateIcurveGpmUi", js)
        self.assertIn("renderIcurveLab", js)
        self.assertIn("runIcurveAnalysis", js)
        self.assertIn("buildIcurveFormData", js)
        self.assertIn("initIcurveGeometricLab", js)
        self.assertIn("ikurve-geometric-matrix-a", js)
        self.assertIn("runIcurveSpectroscope", js)
        self.assertIn("lockIcurveIngest", js)
        self.assertIn("isIcurveIngestLocked()", js)
        self.assertIn("ikurve-ingest-locked", js)
        self.assertIn("ikurve-ingest-lock-banner", js)
        self.assertNotIn("initIcurveEditors", js)
        self.assertNotIn("ikurve-text-a", js)
        self.assertIn("ICURVE_FETCH_TIMEOUT_MS", js)
        self.assertIn("currentAnalysis", js)
        self.assertIn("/api/cipher/encrypt", js)
        self.assertIn("/api/cipher/decrypt", js)
        self.assertIn("cipher-form", js)
        self.assertIn("refreshGpmEncryptPanel", js)
        self.assertIn("gpm-encrypt-enable", js)
        self.assertIn("renderCellTwinsBanner", js)
        self.assertIn("renderCellGeometryBlock", js)
        self.assertIn("renderSignalOverview", js)
        self.assertIn("renderLanguageDbCard", js)
        self.assertIn("renderWordGeometryBadges", js)
        self.assertIn("db_audit_mode", js)
        self.assertIn("renderRelationOverlap", js)
        self.assertIn("openIcurveWithText", js)
        self.assertIn("ikurve-cell-twins-banner", js)
        self.assertIn("ikurve-signal-overview", js)

    def test_ikurve_lab_js(self):
        js = (ROOT / "web" / "static" / "ikurve_lab.js").read_text(encoding="utf-8")
        self.assertIn("window.currentAnalysis", js)
        self.assertIn("IKURVE_MODE_DEFAULTS", js)
        self.assertIn("paragraph:", js)
        self.assertIn("setIcurveChartScale", js)
        self.assertIn("data-ikurve-chart-scale", js)
        self.assertIn("Kürzere als Maß", js)
        self.assertIn("ikurve-chart-scale", js)
        self.assertIn("dataKey: 'paragraphs'", js)
        self.assertIn("dtwKey: 'paragraph'", js)
        self.assertIn("label: 'Absatz'", js)
        self.assertIn("renderIcurveLab", js)
        self.assertIn("ikurve-layer-switch", js)
        self.assertIn("ikurve-zone", js)
        self.assertIn("aria-live", js)
        self.assertIn("ikurve-layer-active", js)
        self.assertIn("ikurve-depth-active", js)
        self.assertIn("patchIcurveLabView", js)
        self.assertIn("data-ikurve-zone", js)
        self.assertIn("renderForeignTokenAuditCompact", js)
        self.assertIn("CRITICAL_ANOMALY", js)
        self.assertIn("HOHE ENTROPIE", js)
        self.assertIn("HYBRIDE / SCHWACHE MATRIX", js)
        self.assertIn("UNDEFINIERTE", js)
        self.assertIn("Abweichende DB-Zuordnung (Richtwert)", js)
        self.assertNotIn("Fremdkörper", js)
        self.assertNotIn("Verschleierung", js)
        self.assertNotIn("Chiffrierungs-Verdacht", js)
        self.assertIn("ikurve-badge-red", js)
        self.assertIn("ikurve-badge-yellow", js)
        self.assertIn("db_speech_audit", js)
        self.assertIn("renderEnjambementBadge", js)
        self.assertIn("downsampleSparklinePoints", js)
        self.assertIn("curvePointCount", js)
        self.assertIn("ikurve-sparkline-hint", js)
        self.assertIn("ikurve-cell-nested", js)
        self.assertIn("renderAtomicForensicsMetrics", js)
        self.assertIn("renderZone2AtomicForensics", js)
        self.assertIn("ggt_kgv_ratio", js)

    def test_v49_audit_wording_in_app_js(self):
        js = (ROOT / "web" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn("Sprache &amp; DB-Abdeckung (Richtwert)", js)
        self.assertIn("Abweichende DB-Zuordnung (Beispiele)", js)
        self.assertIn("Mischsignal in der DB-Matrix", js)
        self.assertNotIn("Fremdkörper", js)
        self.assertNotIn("Verschleierung", js)
        self.assertNotIn("Sprache unsicher — Audit über Score-Tendenz", js)

    def test_normalization_help_used_on_page(self):
        from pipeline.normalize import CIPHER_HELP, DIFF_HELP, INDEX_HELP, MATCHING_HELP, NORMALIZATION_HELP

        with app.test_client() as client:
            html = client.get("/").data.decode("utf-8")

        self.assertIn(NORMALIZATION_HELP["eszett"], html)
        self.assertIn(NORMALIZATION_HELP["eszett_example_1"], html)
        self.assertIn(NORMALIZATION_HELP["decode_result"], html)
        self.assertIn(NORMALIZATION_HELP["compare"], html)
        self.assertIn(NORMALIZATION_HELP["eszett_compare"], html)
        self.assertIn(MATCHING_HELP["lcm_example"], html)
        self.assertIn(DIFF_HELP["intro"], html)
        self.assertIn(INDEX_HELP["intro"], html)
        self.assertIn(INDEX_HELP["meta_genome"], html)
        self.assertIn(INDEX_HELP["meta_language"], html)
        self.assertIn(CIPHER_HELP["intro"], html)
        self.assertIn(CIPHER_HELP["gpm_encrypt"], html)
        self.assertIn("Primzahl 103", html)
        self.assertNotIn("ss/SS", html)
        # Norm-Regeltabelle nur einmal (Tab Konzept)
        self.assertEqual(html.count('class="norm-rules"'), 1)
        konzept_end = html.find('id="tab-encodieren"')
        self.assertGreater(konzept_end, 0)
        self.assertIn('class="norm-rules"', html[:konzept_end])

    def test_homepage_tab_markup(self):
        from pipeline.normalize import DIFF_HELP

        with app.test_client() as client:
            resp = client.get("/")
            self.assertEqual(resp.status_code, 200)
            html = resp.data.decode("utf-8")

        tabs = ["konzept", "encodieren", "decodieren", "wortpaar", "ikurve", "gpm", "datenbank"]
        for tab in tabs:
            self.assertIn(f'data-tab="{tab}"', html)
            self.assertIn(f'id="tab-{tab}"', html)

        self.assertEqual(len(re.findall(r'class="tab-btn', html)), 7)
        self.assertIn('class="tool-page-head"', html)
        self.assertIn('id="gpm-cipher-section"', html)
        self.assertIn('id="wortpaar-form"', html)
        self.assertIn('name="pair-mode"', html)
        self.assertIn('id="tab-vergleichen"', html)
        self.assertIn('id="tab-differenz"', html)
        self.assertIn('id="tab-verschluesseln"', html)
        self.assertIn('type="button"', html)
        self.assertIn("/static/app.js", html)
        self.assertIn("/static/style.css", html)
        self.assertIn("gpm-compile-form", html)
        self.assertIn("2026.06-gpm-v49", html)
        self.assertIn("Die Oberfläche", html)
        self.assertIn("Das .gpm-Format (v7 — verlustfrei)", html)
        self.assertIn("Zell-Geometrie", html)
        self.assertIn("favicon.svg", html)
        self.assertIn("?v=57", html)
        self.assertIn("ikurve-geometric-matrix-a", html)
        self.assertIn("ikurve-ingest-root", html)
        self.assertIn("ikurve-ingest-lock-banner", html)
        self.assertIn("ikurve-spectro-btn-a", html)
        self.assertIn("Selektion analysieren", html)
        self.assertNotIn("ikurve-text-a", html)
        self.assertIn("ikurve_lab.js", html)
        self.assertIn("geometric_editor.js", html)
        self.assertIn("gpm-geometric-viewport", html)
        self.assertNotIn("gpm-spectro-mirror", html)
        self.assertIn("ikurve-db-audit-mode", html)
        self.assertNotIn("ikurve-semantic-zoom", html)
        self.assertNotIn("Section-Table", html)
        self.assertNotIn("S/I-Stufen", html)
        self.assertNotIn("Straße</code> →", html)
        self.assertIn('value="lcm"', html)
        self.assertIn("Wortpaar", html)
        self.assertIn(DIFF_HELP["intro"], html)
        self.assertIn('data-tab="wortpaar"', html)
        self.assertIn('data-tab="ikurve"', html)
        self.assertNotIn('data-tab="verschluesseln"', html)
        self.assertIn("Index-Vektoren", html)
        self.assertIn("S(I)-Verschlüsselung", html)
        self.assertIn("code-editor", html)
        self.assertIn("gpm-load-gpm-btn", html)
        self.assertIn("gpm-gpm-file", html)
        self.assertIn("gpm-editor-dropzone", html)
        self.assertIn("ikurve-gpm-drop-a", html)
        self.assertIn("gpm-read-dropzone", html)
        self.assertIn("editor-shell", html)

    def test_handler_modules_on_disk(self):
        handler_files = (
            "system.py",
            "encode.py",
            "decode.py",
            "compare.py",
            "diff.py",
            "icurve.py",
            "cipher.py",
            "gpm.py",
            "size.py",
            "payloads.py",
            "_repo.py",
            "_steps.py",
        )
        for name in handler_files:
            self.assertTrue((ROOT / "web" / "handlers" / name).is_file(), name)

    def test_cell_twins_banner_css(self):
        css = (ROOT / "web" / "static" / "style.css").read_text(encoding="utf-8")
        self.assertIn(".ikurve-cell-twins-banner", css)
        self.assertIn(".ikurve-metrics-cell", css)
        self.assertIn(".cell-geometry-block", css)
        self.assertIn(".ikurve-signal-overview", css)
        self.assertIn("margin-top: auto", css)
        self.assertIn(".ikurve-chart-scale", css)
        self.assertIn(".ikurve-sparkline-scroll", css)
        self.assertIn("width: 100%", css)
        self.assertIn(".ikurve-atomic-metrics", css)
        self.assertIn(".ikurve-substance-twins-banner", css)
        self.assertIn(".ikurve-relation-twins-banner", css)
        self.assertIn(".ikurve-badge-offset", css)
        self.assertIn(".ikurve-charts-paired", css)
        self.assertIn(".ikurve-foreign-audit", css)
        self.assertIn(".ikurve-layer-switch", css)
        self.assertIn(".ikurve-depth-pills", css)
        self.assertIn(".ikurve-layer-active", css)
        self.assertIn(".ikurve-zone", css)
        self.assertIn(".geometric-matrix", css)
        self.assertIn(".ikurve-ingest-locked", css)
        self.assertIn(".ikurve-ingest-lock-banner", css)
        self.assertIn("user-select: text", css)
        self.assertIn(".ikurve-badge-purple", css)
        self.assertIn(".ikurve-badge-red", css)
        self.assertIn(".ikurve-badge-yellow", css)
        self.assertIn(".ikurve-sparkline-hint", css)
        self.assertIn(".ikurve-cell-nested", css)
        with app.test_client() as client:
            for path in ("/static/app.js", "/static/ikurve_lab.js", "/static/style.css"):
                resp = client.get(path)
                try:
                    self.assertEqual(resp.status_code, 200, path)
                    self.assertGreater(len(resp.data), 100, path)
                    cache = resp.headers.get("Cache-Control", "")
                    self.assertIn("no-store", cache, path)
                finally:
                    resp.close()


if __name__ == "__main__":
    unittest.main()
