import type { ExplainArticleMeta, ExplainExampleBlock, ExplainWorkbenchStep } from "./articles";

const wb = (
  where: string,
  action: string,
  outcome: string,
): ExplainWorkbenchStep => ({ where, action, outcome });

const ex = (
  code: string,
  rows: ExplainExampleBlock["rows"],
  title?: string,
): ExplainExampleBlock => ({ code, rows, title });

export const EXPLAIN_ARTICLES_DATA: ExplainArticleMeta[] = [
  {
    slug: "00-einstieg",
    section: "grundlagen",
    title: "Einstieg",
    summary: "GPM-Konzept: S(I) und alle Identitätstypen",
    atAGlance: [
      "GPM speichert Wörter als Paar (S, I) — Substanz + Permutations-Index.",
      "Anagramme teilen S, unterscheiden sich in I.",
      "Weitere Typen: N(I), D(I), H(I) für Zahlen, Dezimal und Hybrid.",
      "Die Workbench zeigt jeden Schritt als nachvollziehbare Pedagogik.",
    ],
    workbench: [
      wb("Tab S(I) → Encodieren", "Wort eingeben, Profil wählen", "S, I und Rechenschritte"),
      wb("Tab Vergleichen", "LISTEN vs. SILENT", "Gleiches S, verschiedenes I"),
      wb("Tab GPM", "Kurzen Text kompilieren", "Header, Tokens, Gaps"),
    ],
    related: ["01-substanz-s", "02-index-i", "04-ni-ganzzahl"],
    cta: { type: "encode", demoText: "LISTEN" },
    showSiFormula: true,
  },
  {
    slug: "01-substanz-s",
    section: "grundlagen",
    title: "Substanz S",
    summary: "Primzuordnung, Multimenge, Anagramm-Invariante",
    atAGlance: [
      "S ist das Primzahlprodukt der Buchstaben-Multimenge.",
      "Reihenfolge spielt für S keine Rolle — LISTEN und SILENT haben dasselbe S.",
      "S eignet sich für ggT/kgV-Vergleiche ohne Rohtext.",
    ],
    workbench: [
      wb("Tab S(I) → Encodieren", "Wort encodieren", "Substanz-Wert und Primfaktoren in Steps"),
      wb("Tab Vergleichen → Wortpaar", "Zwei Wörter vergleichen", "ggT, kgV, Klassifikation"),
    ],
    examples: [ex("LISTEN / SILENT", [{ label: "LISTEN", value: "S*", kind: "S" }, { label: "SILENT", value: "S* (gleich)", kind: "S" }])],
    related: ["02-index-i", "09-ggt-kgv"],
    cta: { type: "compare", wordA: "LISTEN", wordB: "SILENT" },
    miniCalc: "encode",
    showSiFormula: true,
  },
  {
    slug: "02-index-i",
    section: "grundlagen",
    title: "Index I",
    summary: "Permutations-Rang, N_perm, Sk/Sp/Lut",
    atAGlance: [
      "I kodiert die Reihenfolge als Rang im Permutationsraum N_perm.",
      "Gleiche Multimenge, verschiedene Anordnung → gleiches S, verschiedenes I.",
      "Sk/Sp/Lut sind alternative Sequenz-Identitäten aus der OG-Pipeline.",
    ],
    workbench: [
      wb("Tab S(I) → Encodieren", "Anagramm-Paar encodieren", "Gleiches S, unterschiedliches I"),
      wb("Tab Vergleichen → I-Kurve", "Zwei Dokumente laden", "I-Verlauf als Sparkline"),
    ],
    related: ["01-substanz-s", "20-i-curve"],
    cta: { type: "encode", demoText: "SILENT" },
    miniCalc: "encode",
    showSiFormula: true,
  },
  {
    slug: "03-decode",
    section: "grundlagen",
    title: "Decode",
    summary: "ingredients → perm_decode → Text",
    atAGlance: [
      "Decode zerlegt S in die Multimenge (ingredients).",
      "perm_decode rekonstruiert die Zeichenfolge aus I.",
      "Case-Code und explicit[] stellen die Original-Schreibweise wieder her.",
    ],
    workbench: [
      wb("Tab S(I) → Decodieren", "S und I eingeben", "Rekonstruierter Text + Steps"),
      wb("Tab GPM", "Dokument rekonstruieren", "Roundtrip-Badge prüfen"),
    ],
    related: ["01-substanz-s", "02-index-i", "07-normalisierung"],
    cta: { type: "decode" },
    miniCalc: "decode",
    showSiFormula: true,
  },
  {
    slug: "04-ni-ganzzahl",
    section: "grundlagen",
    title: "N(I) — Ganzzahl",
    summary: "Numerische Literale, canonical_n, Code-Modus",
    atAGlance: [
      "N(I) kodiert Ganzzahlen getrennt von Wort-S(I).",
      "Führende Nullen werden kanonisch entfernt: 0042 → 42.",
      "Im Code-Modus erzeugt der Lexer PointerKind.N.",
    ],
    workbench: [
      wb("Tab GPM → Modus Code", "Zahlenliteral z. B. x = 42", "Registry-Eintrag N"),
      wb("Panel Registry", "Nach Kompilierung öffnen", "Payload-Typ N sichtbar"),
    ],
    examples: [ex("0042", [{ label: "Eingabe", value: "0042" }, { label: "Kanonisch", value: "42", kind: "N" }])],
    related: ["05-di-dezimal", "06-hi-hybrid-identitaet", "17-payload-kinds"],
    cta: { type: "gpm", demoText: "x = 42\n" },
  },
  {
    slug: "05-di-dezimal",
    section: "grundlagen",
    title: "D(I) — Dezimal",
    summary: "Bruchrelation, exakte Dezimal-Roundtrips",
    atAGlance: [
      "D(I) speichert Dezimalbrüche exakt als Zähler/Nenner/ggT.",
      "Kein IEEE-Float — bitgenauer rationaler Roundtrip.",
      "Typisch in Code-Literalen wie 3.14.",
    ],
    workbench: [
      wb("Tab GPM → Modus Code", "Dezimal-Literal eingeben", "Registry-Eintrag D"),
      wb("Rekonstruieren", "Roundtrip auslösen", "Exakter Dezimalstring"),
    ],
    examples: [ex("3.14", [{ label: "Literal", value: "3.14", kind: "D" }, { label: "Speicherung", value: "Bruchrelation" }])],
    related: ["04-ni-ganzzahl", "17-payload-kinds"],
    cta: { type: "gpm", demoText: "pi = 3.14\n" },
  },
  {
    slug: "06-hi-hybrid-identitaet",
    section: "grundlagen",
    title: "H(I) — Hybrid",
    summary: "S- und N-Segmente in einer Zeichenkette",
    atAGlance: [
      "H(I) parst gemischte Ketten links-nach-rechts in S- und N-Läufe.",
      "abc123def → Segmente S, N, S — mindestens zwei verschiedene Tags.",
      "Reine Wörter oder reine Zahlen sind kein H(I).",
    ],
    workbench: [
      wb("Tab GPM → Code/Hybrid", "Gemischtes Literal", "H-Eintrag in Registry"),
      wb("Panel Steps", "Segment-Liste prüfen", "Tags S und N in Reihenfolge"),
    ],
    examples: [
      ex("abc123def", [
        { label: "abc", value: "S", kind: "S" },
        { label: "123", value: "N", kind: "N" },
        { label: "def", value: "S", kind: "S" },
      ]),
    ],
    related: ["04-ni-ganzzahl", "23-hybrid-fences"],
    cta: { type: "gpm", demoText: "id = abc123\n" },
  },
  {
    slug: "07-normalisierung",
    section: "grundlagen",
    title: "Normalisierung",
    summary: "NFC, prepare_substrate, Profil-Whitelist",
    atAGlance: [
      "prepare_substrate normalisiert Rohtext vor S/I-Berechnung.",
      "NFC, Groß/Klein und Zeichen-Whitelist sind profilabhängig.",
      "OG vs. Roman-Profil kann gleiches Wort unterschiedlich kodieren.",
    ],
    workbench: [
      wb("Tab S(I) → Encodieren", "Profil wechseln, gleiches Wort", "Anderes S/I bei anderem Profil"),
      wb("Tab GPM", "Profil im Editor wählen", "GpmDocument.profile gesetzt"),
    ],
    related: ["08-profile", "03-decode"],
    cta: { type: "encode", demoText: "Müller" },
  },
  {
    slug: "08-profile",
    section: "grundlagen",
    title: "Profile",
    summary: "33 Schriftsätze",
    atAGlance: [
      "33 AlphabetProfile steuern Primzuordnung und Lex-Order.",
      "og (Original-German) ist der Standard in Tutorials.",
      "GET /api/profiles liefert die Workbench-Auswahl.",
    ],
    workbench: [
      wb("ProfilePicker", "Profil wählen", "Wirkt auf Encode, Kompilierung, Korpus"),
      wb("Tab Datenbank", "Korpus nach Profil", "Partitionierte Suche"),
    ],
    related: ["07-normalisierung", "01-substanz-s"],
    cta: { type: "encode", demoText: "HALLO" },
  },
  {
    slug: "09-ggt-kgv",
    section: "vergleich",
    title: "ggT / kgV",
    summary: "Substanz-Vergleich auf Primfaktoren",
    atAGlance: [
      "ggT misst gemeinsame Buchstaben-Multiplizitäten zweier Substanzen.",
      "kgV ist die vereinigte Primhülle beider Wörter.",
      "LISTEN/SILENT: ggT = kgV = S (Anagramm).",
    ],
    workbench: [
      wb("Tab Vergleichen → Wortpaar", "Zwei Wörter eingeben", "ggT, kgV, Ratio"),
      wb("Tab Vergleichen → Dokumente", "Tier-Slider nutzen", "Gestaffelter Dokument-Vergleich"),
    ],
    examples: [ex("LISTEN / SILENT", [{ label: "ggT", value: "S*" }, { label: "kgV", value: "S*" }])],
    related: ["10-wortpaar-diff", "01-substanz-s"],
    cta: { type: "compare", wordA: "LISTEN", wordB: "SILENT" },
    miniCalc: "compare",
  },
  {
    slug: "10-wortpaar-diff",
    section: "vergleich",
    title: "Wortpaar-Diff",
    summary: "Klassifikation: identisch, Anagramm, Teilmenge, disjoint",
    atAGlance: [
      "analyze_word_pair liefert algebraische Klassifikation.",
      "Anagramm = gleiches S, verschiedenes I.",
      "API-Antwort enthält explain_links zu passenden Kapiteln.",
    ],
    workbench: [
      wb("Tab Vergleichen → Wortpaar", "Modus diff", "Klassifikations-Badge + Steps"),
      wb("Erklärungen-Link", "Aus API-Antwort", "Springt zu diesem Kapitel"),
    ],
    related: ["09-ggt-kgv", "11-wortpaar-anagramm"],
    cta: { type: "compare", wordA: "LISTEN", wordB: "SILENT" },
    miniCalc: "compare",
  },
  {
    slug: "11-wortpaar-anagramm",
    section: "vergleich",
    title: "Wortpaar-Anagramm",
    summary: "Anagramm-Suche im Roman-Alpha-Korpus",
    atAGlance: [
      "Suche nach gleicher Substanz S, verschiedenem I.",
      "Nutzt SQLite-Korpus ge_prime_roman_alpha_alt.",
      "LISTEN findet SILENT als Treffer.",
    ],
    workbench: [
      wb("Tab Datenbank", "Anagramm-Suche", "Trefferliste mit Substanz-Match"),
      wb("API", "POST /api/compare/anagram-search", "word + profile + limit"),
    ],
    related: ["10-wortpaar-diff", "21-corpus"],
    cta: { type: "compare", wordA: "LISTEN", wordB: "SILENT" },
    miniCalc: "compare",
  },
  {
    slug: "12-gaps-dokument",
    section: "dokument",
    title: "Gaps & Dokument",
    summary: "n Token → n+1 Gaps — Gap-Symmetrie",
    atAGlance: [
      "Volltext = gap[0] + token[0] + gap[1] + … + gap[n].",
      "Invariante: len(gaps) == len(tokens) + 1.",
      "Rekonstruktion verketten Gaps und dekodierte Tokens.",
    ],
    workbench: [
      wb("Tab GPM", "Text kompilieren", "Tabs Gaps / Tokens / Registry"),
      wb("Rekonstruieren", "Roundtrip prüfen", "Badge zeigt Übereinstimmung"),
      wb("In Vergleichen öffnen", "Session-Freeze", "Eingefrorene Kopie"),
    ],
    related: ["15-registry", "16-tokens", "13-gpm-binary"],
    cta: { type: "gpm", demoText: "Hallo Welt.\n" },
  },
  {
    slug: "13-gpm-binary",
    section: "dokument",
    title: "GPM Binary",
    summary: "Container-Format .gpm, Magic, Version 9",
    atAGlance: [
      "Magic GPM, Version 9 ist Standard (Profil, Block-Tree, GAP-RLE).",
      "write_gpm → read_gpm → reconstruct_text muss bitgenau sein.",
      "Verschlüsselt: Magic GPC\\x01 — siehe Kapitel 28.",
    ],
    workbench: [
      wb("Tab GPM", "Drag&Drop .gpm", "Header, Tokens, Gaps anzeigen"),
      wb("Export", "Nach Kompilierung", ".gpm-Datei speichern"),
    ],
    related: ["12-gaps-dokument", "28-cipher-gpc"],
    cta: { type: "gpm", demoText: "Hallo.\n" },
  },
  {
    slug: "14-case-explicit",
    section: "dokument",
    title: "Case & Explicit",
    summary: "case_code und explicit[] für Schreibweisen",
    atAGlance: [
      "case_code kodiert Groß/Klein relativ zur Normalform.",
      "explicit[] für Ausnahmen, die Case-Policy nicht abdeckt.",
      "Perm-Raum arbeitet immer auf normalized.",
    ],
    workbench: [
      wb("Tab GPM → Steps", "Nach Kompilierung", "Case-Schritte pro Token"),
      wb("Rekonstruieren", "Listen vs. listen", "Case ohne explicit"),
    ],
    related: ["07-normalisierung", "16-tokens"],
    cta: { type: "gpm", demoText: "Listen\n" },
  },
  {
    slug: "15-registry",
    section: "dokument",
    title: "Registry",
    summary: "Header und DocumentRegistry",
    atAGlance: [
      "Header: NL-Wörter mit S und normalized.",
      "DocumentRegistry: N, D, H, C für Code und Geometrie.",
      "Body referenziert nur IDs — Wörter einmal gespeichert.",
    ],
    workbench: [
      wb("Tab GPM → Registry", "Nach Kompilierung", "Header + Code-Einträge"),
      wb("Modi NL / Code / Hybrid", "Vergleichen", "Unterschiedliche Registry-Füllung"),
    ],
    related: ["16-tokens", "17-payload-kinds"],
    cta: { type: "gpm", demoText: "Test\n" },
  },
  {
    slug: "16-tokens",
    section: "dokument",
    title: "Tokens",
    summary: "word_id + perm_index im Body",
    atAGlance: [
      "Jedes Token: word_id → Header, perm_index → I dieses Vorkommens.",
      "Gleiches Wort, andere Anordnung: gleiche word_id, anderes I.",
      "payload_kind standardmäßig S für NL.",
    ],
    workbench: [
      wb("Tab GPM → Tokens", "Nach Kompilierung", "word_id, perm_index, case_code"),
      wb("Klick auf word_id", "Header-Detail", "Substanz S des Worts"),
    ],
    related: ["15-registry", "02-index-i"],
    cta: { type: "gpm", demoText: "ab ba\n" },
  },
  {
    slug: "17-payload-kinds",
    section: "dokument",
    title: "Payload-Kinds",
    summary: "Zeiger S, N, D, H, C",
    atAGlance: [
      "kind + ptr_id verweisen in die passende Registry-Tabelle.",
      "structural_only für Redundanz ohne Substanz-Inhalt.",
      "Code-Literale nutzen N, D, H statt S.",
    ],
    workbench: [
      wb("Tab GPM → Registry", "Code kompilieren", "Einträge nach Kind gruppiert"),
      wb("Redundanz-Job", "structural_only filtern", "Nur Struktur-Zeiger"),
    ],
    related: ["04-ni-ganzzahl", "18-blocks"],
    cta: { type: "gpm", demoText: "x = abc123\n" },
  },
  {
    slug: "18-blocks",
    section: "dokument",
    title: "Blocks",
    summary: "root_block und AST-Hierarchie",
    atAGlance: [
      "BlockNode-Baum: MODULE, CODE_BLOCK, PARAGRAPH, SENTENCE, CELL.",
      "sequence enthält geordnete PointerRef-Listen.",
      "Hybrid und Code materialisieren root_block.",
    ],
    workbench: [
      wb("Tab GPM → Steps", "Hybrid/Code", "Block-Hierarchie"),
      wb("Export v9", "FLAG_BLOCK_TREE", "Baum in .gpm eingebettet"),
    ],
    related: ["24-code-blocks", "23-hybrid-fences"],
    cta: { type: "gpm", demoText: "# Titel\n\nText.\n" },
  },
  {
    slug: "19-cells",
    section: "dokument",
    title: "Cells",
    summary: "Zell-Geometrie und I-Kurve",
    atAGlance: [
      "materialize_geometry erzeugt cells[] und hierarchy.",
      "Zellen partitionieren Tokens für I-Kurven.",
      "perm_index / perm_space pro Zelle relevant.",
    ],
    workbench: [
      wb("Tab GPM", "Geometrie materialisieren", "Zell-Infos in Steps"),
      wb("Tab Vergleichen → I-Kurve", "Zwei Dokumente", "Zell-Matrix"),
    ],
    related: ["20-i-curve", "02-index-i"],
    cta: { type: "ikurve" },
  },
  {
    slug: "20-i-curve",
    section: "analyse",
    title: "I-Kurve",
    summary: "Perm-Verlauf, Zonen, Downsampling",
    atAGlance: [
      "I-Kurve = perm_index/perm_space entlang des Dokuments.",
      "Max. 512 Sparkline-Punkte (Downsampling-Invariante B).",
      "Vier Achsen: substance, token_i, cell_i, hierarchy.",
    ],
    workbench: [
      wb("Tab Vergleichen → I-Kurve", "Zwei Dokumente laden", "Sparklines + Matrix"),
      wb("Spectroscope-Link", "Aus I-Kurve", "Token-Spans im Detail"),
    ],
    related: ["19-cells", "26-spectroscope"],
    cta: { type: "ikurve" },
  },
  {
    slug: "21-corpus",
    section: "analyse",
    title: "Korpus",
    summary: "Basis-Index und Ähnlichkeitssuche",
    atAGlance: [
      "Invertierter Index über Dokument-Signaturen.",
      "Zwei-Stufen-Suche: Kandidaten, dann tiered compare.",
      "Datenbank-Tab zeigt Korpus-Statistiken.",
    ],
    workbench: [
      wb("Tab Datenbank", "Statistiken", "Wortanzahl, Substanz-Verteilung"),
      wb("Anagramm-Suche", "Verknüpft", "Roman-Alpha-Korpus"),
    ],
    related: ["11-wortpaar-anagramm", "22-redundanz"],
    cta: { type: "compare", wordA: "LISTEN", wordB: "SILENT" },
  },
  {
    slug: "22-redundanz",
    section: "analyse",
    title: "Redundanz",
    summary: "Gleitende Fenster, Job-Scan",
    atAGlance: [
      "Adaptive Fenster [8, 12, 16, 20, 24, 28] Token.",
      "index_only-Modus ohne Voll-Rekompilierung.",
      "structural_only-Pointer ausblendbar.",
    ],
    workbench: [
      wb("Jobs-Panel", "Redundanz-Job starten", "Fortschritt + Trefferliste"),
      wb("Treffer", "Sprung zur Position", "Token-Index im Dokument"),
    ],
    related: ["21-corpus", "17-payload-kinds"],
    cta: { type: "gpm", demoText: "a a a a a\n" },
  },
  {
    slug: "23-hybrid-fences",
    section: "code",
    title: "Hybrid-Fences",
    summary: "Invariante A — Fences nie in NL-Registry",
    atAGlance: [
      "Fence-Inhalt nur in fence_boundaries und Code-Blöcken.",
      "NL-Registry und NL-Gaps enthalten keinen Fence-Text.",
      "compile_hybrid segmentiert NL und CODE.",
    ],
    workbench: [
      wb("Tab GPM → Hybrid", "Markdown mit ``` fences", "Fences separat im Panel"),
      wb("Registry prüfen", "Fence-Zeilen fehlen", "Invariante A sichtbar"),
    ],
    related: ["24-code-blocks", "12-gaps-dokument"],
    cta: { type: "gpm", demoText: "Text\n\n```py\nx = 1\n```\n" },
  },
  {
    slug: "24-code-blocks",
    section: "code",
    title: "Code-Blöcke",
    summary: "compile_source → root_block → Roundtrip",
    atAGlance: [
      "Code wird als Block-Baum + Registry gespeichert, nicht als NL-String.",
      "compile_source / reconstruct_source für reinen Code.",
      "Hybrid mischt NL-Segmente und Code-Fences.",
      "Export v9 bettet den Block-Baum ein (FLAG_BLOCK_TREE).",
    ],
    workbench: [
      wb("Tab GPM → Modus Code", "Quelltext eingeben, Kompilieren", "Block-Baum und Registry im Steps-Panel"),
      wb("Tab GPM → Modus Hybrid", "NL + Markdown-Fences", "Segmente getrennt, kein Fence in NL-Registry"),
      wb("Panel Steps", "Nach Kompilierung", "root_block, PointerRefs, Registry-Einträge"),
    ],
    workbenchTip: "Export als v9 setzt FLAG_BLOCK_TREE — der Block-Baum steckt in der .gpm-Datei.",
    examples: [
      ex("answer = 42", [
        { label: "answer", value: "Identifier", kind: "S" },
        { label: "42", value: "Literal", kind: "N" },
        { label: "=", value: "Operator", kind: "C" },
      ]),
    ],
    related: ["18-blocks", "17-payload-kinds", "25-cipher"],
    cta: { type: "gpm", demoText: "answer = 42\n" },
  },
  {
    slug: "25-cipher",
    section: "code",
    title: "S(I)-Cipher",
    summary: "Modi word, prime, si, hardcore",
    atAGlance: [
      "Cipher-Dialog im GPM-Tab verschlüsselt Klartext.",
      "Modi: word, prime, si, hardcore.",
      "Algorithmus ≠ GPC-Dateihülle (Kapitel 28).",
    ],
    workbench: [
      wb("Tab GPM → Cipher", "Passwort + Modus wählen", "Base64-Ciphertext"),
      wb("API /api/cipher", "encrypt / decrypt", "Ohne Datei-Container"),
    ],
    related: ["28-cipher-gpc", "03-decode"],
    cta: { type: "gpm", demoText: "LISTEN" },
  },
  {
    slug: "26-spectroscope",
    section: "code",
    title: "Spectroscope",
    summary: "Token-Span-Analyse",
    atAGlance: [
      "Char-genaue Token-Spannen über den Rohtext.",
      "Ergänzt I-Kurve mit lokalem Zoom.",
      "API: POST /api/editor/spectroscope.",
    ],
    workbench: [
      wb("Aus I-Kurve", "Spectroscope öffnen", "Spans über Text"),
      wb("Editor", "Nach Kompilierung", "Token-Metadaten pro Span"),
    ],
    related: ["20-i-curve", "16-tokens"],
    cta: { type: "ikurve" },
  },
  {
    slug: "27-inference-trace",
    section: "code",
    title: "Inference-Trace",
    summary: "Schritt-Protokoll Encode/Decode",
    atAGlance: [
      "InferenceTrace protokolliert Normalisierung → S → I.",
      "Pedagogik ohne Doppel-Encode.",
      "Steps in API und Mini-Rechner.",
    ],
    workbench: [
      wb("Tab S(I)", "Encodieren mit Steps", "Trace-Einträge"),
      wb("API calc", "include_trace wo unterstützt", "Vollständige Kette"),
    ],
    related: ["01-substanz-s", "03-decode"],
    cta: { type: "encode", demoText: "LISTEN" },
  },
  {
    slug: "28-cipher-gpc",
    section: "code",
    title: "GPC-Hülle",
    summary: "Verschlüsselte .gpm, Magic GPC\\x01",
    atAGlance: [
      "GPC\\x01 umschließt verschlüsselte GPM-Nutzlast.",
      "Ohne Schlüssel: error.code cipher_key_required.",
      "decrypt_gpm_file → innere GPM-Bytes → read_gpm.",
    ],
    workbench: [
      wb("Tab GPM → Export verschlüsselt", "Passwort eingeben", "Datei beginnt mit GPC\\x01"),
      wb("Import", "Passwort-Dialog", "Entschlüsselung → normales Dokument"),
    ],
    related: ["25-cipher", "13-gpm-binary"],
    cta: { type: "gpm", demoText: "Geheim.\n" },
  },
];
