export const gpm = {
  title: "GPM Datei",
  lead: "Text kompilieren, lesen, verschlüsseln und im Dokument suchen",
  formatTitle: "Format v9",
  formatLead: "Binärer .gpm-Stream mit Registry, Gaps und Substanz-Layer.",
  workspace: {
    formatBadge: "Format v9",
    dropOverlay: "Text- oder .gpm-Datei ablegen",
    fileLabel: "Quelltext",
    exportName: "Dateiname",
    exportSuffixGpm: ".gpm",
    exportSuffixGpc: ".gpc",
    roundtripOk: "Verlustfrei",
    roundtripFail: "Roundtrip abweichend",
    roundtripLabel: "Roundtrip",
  },
  toolbar: {
    cipher: "Verschlüsseln…",
  },
  results: {
    genome: "Genom",
    geometry: "Geometrie",
  },
  cipherDialog: {
    title: "S(I)-Verschlüsselung",
    decryptHint: "Verschlüsselte GPC-Datei — Schlüssel eingeben zum Entschlüsseln.",
    encryptHint: "Quelltext mit S(I)-Cipher verschlüsseln.",
    submit: "Anwenden",
    cancel: "Abbrechen",
  },
  searchPanel: {
    summary: "Suche im Dokument",
    genomeOnlyHint:
      "ggT und kgV arbeiten auf dem Genom (eindeutige Wörter) — ohne Positions-Index und ohne S(I)-Paar pro Vorkommen.",
  },
  editorTitle: "Editor",
  sourceLabel: "Quelltext",
  sourcePlaceholder: "Text eingeben oder Datei ablegen…",
  compile: "Kompilieren",
  clear: "Leeren",
  readFile: "Datei laden",
  stats: "Statistik",
  download: "Download",
  keyLabel: "Schlüssel",
  cipherModes: {
    word: "Wort",
    prime: "Primzahl",
    si: "S+I",
    hardcore: "Hardcore",
  },
  searchQuery: "Suchwort",
  searchQuery2: "Zweites Wort (kgV)",
  searchHits: "Treffer",
  searchModes: {
    substance: "Substanz exakt",
    gcd: "ggT-Filter",
    lcm: "kgV (2 Wörter)",
  },
  searchSubmit: "Suchen",
  openInICurve: "In I-Kurve vergleichen",
  tables: {
    genome: "Genom (eindeutige Wörter)",
    geometry: "Geometrie (Vorkommen)",
    word: "Wort",
    wordId: "Wort-ID",
    substance: "Substanz S",
    siPair: "S(I)",
    position: "Position",
    gcd: "ggT",
  },
  empty: "Kompilieren oder .gpm laden.",
  loading: "Verarbeite…",
} as const;
