export const gpm = {
  title: "GPM Datei",
  lead: "Text kompilieren, lesen, verschlüsseln und im Dokument suchen",
  formatTitle: "Format v7",
  formatLead: "Binärer .gpm-Stream mit Registry, Gaps und Substanz-Layer.",
  workspace: {
    formatBadge: "Format v7",
    dropOverlay: ".gpm-Datei ablegen",
    docRef: "Dokument",
    fileLabel: "Quelltext",
  },
  toolbar: {
    cipher: "Verschlüsseln…",
  },
  results: {
    registry: "Registry",
    tokens: "Tokens",
    reconstruct: "Rekonstruktion",
  },
  cipherDialog: {
    title: "S(I)-Verschlüsselung",
    decryptHint: "Verschlüsselte GPC-Datei — Schlüssel eingeben zum Entschlüsseln.",
    encryptHint: "Quelltext mit S(I)-Cipher verschlüsseln.",
    submit: "Anwenden",
    cancel: "Abbrechen",
  },
  searchPanel: {
    summary: "Suche im Dokument",
  },
  editorTitle: "Editor",
  sourceLabel: "Quelltext",
  sourcePlaceholder: "Text oder .gpm-Inhalt…",
  compile: "Kompilieren",
  clear: "Leeren",
  readFile: "Datei laden",
  stats: "Statistik",
  download: "Download .gpm",
  reconstruct: "Rekonstruieren",
  cipherTitle: "S(I)-Verschlüsselung",
  encrypt: "Verschlüsseln",
  decrypt: "Entschlüsseln",
  keyLabel: "Schlüssel",
  cipherModes: {
    word: "Wort",
    prime: "Primzahl",
    si: "S+I",
    hardcore: "Hardcore",
  },
  readTitle: "Lesen",
  readHint: ".gpm-Datei ablegen",
  searchTitle: "Suche im Dokument",
  searchQuery: "Suchwort",
  searchQuery2: "Zweites Wort (kgV)",
  searchHits: "Treffer",
  searchMatches: "Treffer",
  searchModes: {
    substance: "Substanz exakt",
    gcd: "ggT-Filter",
    lcm: "kgV (2 Wörter)",
  },
  searchSubmit: "Suchen",
  openInICurve: "In I-Kurve vergleichen",
  spectro: "Selektion analysieren",
  tables: {
    header: "Wörterbuch (Header)",
    tokens: "Token-Stream",
    word: "Wort",
    position: "Position",
  },
  empty: "Kompilieren oder .gpm laden.",
  loading: "Verarbeite…",
} as const;
