export const ikurve = {
  title: "Index-Vektoren — Stil & Geometrie",
  lead: "Zwei Texte — I-Kurven-Vergleich, Meta-Genom und Struktur-Kreuzvalidierung",
  guide:
    "Zwei Texte oder .gpm-Dateien pro Seite — I-Kurve vergleicht Token-I/N-Verhältnisse, Substanz-Ketten und Hierarchie-Ebenen (Phrase, Satz, Absatz, Zeile).",
  decomposition:
    "Pro Token: I = Permutations-Index, N = |Perm-Raum|, i = I/N. Hierarchie-Ebenen nutzen i_phrase_ratio, i_satz_ratio, i_absatz_ratio, i_zeile_ratio.",
  sideA: "Text A",
  sideB: "Text B",
  matrixTitle: "Geometrische Matrix",
  matrixSideA: "Matrix A",
  matrixSideB: "Matrix B",
  substanceA: "Substanz A",
  substanceB: "Substanz B",
  structuralA: "Struktur A",
  structuralB: "Struktur B",
  submit: "Analysieren",
  reset: "Neuer Vergleich",
  locked: "Analyse aktiv — Neuer Vergleich zum Zurücksetzen",
  common: {
    noValue: "—",
    unknown: "?",
    ellipsis: "…",
    separator: " · ",
  },
  sideShort: {
    a: "A",
    b: "B",
  },
  aria: {
    depth: "Tiefe",
    chartScale: "Kurven-Maßstab",
    signalOverview: "Signal-Übersicht",
    axisScores: "Achsen-Fusion",
    sparklinePair: "{a} und {b}",
  },
  labels: {
    sideDepth: "{side} · {depth}",
    dtwDepth: "{depth}-DTW",
  },
  zones: {
    structure: "Struktur-Kreuzvalidierung",
    lens: "Geometrische Linse",
    chains: "Arithmetische Detail-Ketten",
    structureBrief: "{steps} Validierungsschritte",
    lensBrief: "Wort · Substanz · Zelle",
    chainsBrief: "{count} Token",
  },
  modes: {
    atomic: "Wort & Substanz",
    semantic: "Sinn",
    structural: "Raum",
  },
  depth: {
    phrase: "Phrase",
    sentence: "Satz",
    paragraph: "Absatz",
    line: "Zeile",
  },
  chartScale: {
    union: "Gemeinsame Skala",
    shorter: "Kürzere als Maß",
  },
  chartLayout: {
    overlay: "Overlay",
    stacked: "Untereinander",
    legend: "Kurven-Darstellung",
    scrollHint: "Längere Kurve — horizontal scrollen",
    empty: "Keine Knoten ({count}).",
    curveA: "Kurve A ({key})",
    curveB: "Kurve B ({key})",
  },
  levels: {
    word: {
      title: "WORT-EBENE",
      hint: "I pro Token, DTW",
      dtw: "Wort-Geometrie DTW",
      dtwMae: "DTW / MAE",
      literal: "Literal-Match",
    },
    substance: {
      title: "SUBSTANZ-EBENE",
      hint: "ggT/kgV-Kette",
      ggt: "Substanz ggT/kgV",
      twins: "Zwillinge",
      shadows: "Anagramm-Schatten",
    },
    cell: {
      title: "ZELL-EBENE",
      hint: "I_Satz, DTW",
      dtw: "Zell-Score DTW",
      matches: "Matches",
      count: "Zellen A/B",
    },
  },
  structureMatrix: {
    title: "Struktur-Matrix (Kreuzvalidierung)",
    signals: {
      fester_offset_erkannt: "Fester Offset erkannt",
      elastische_streckung: "Elastische Streckung",
      hybride_modifikation: "Hybride Modifikation",
    },
  },
  badges: {
    aria: "Wort-Geometrie-Diagnose",
    offset: "Fester Offset",
    stretch: "Elastische Streckung",
    hybrid: "Teilweise Paraphrase",
  },
  preview: {
    title: "Genom- & Geometrie-Vorschau",
    sideA: "Seite A",
    sideB: "Seite B",
  },
  lensHint: "Sinn/Raum: ein Kurvenpaar pro Ebene (Atomic zeigt Wort + Substanz + Zelle).",
  metrics: {
    fusion: "Gesamt-Fusion",
    wordDtw: "Wort-DTW",
    literal: "Literal-Match",
    tokensA: "Token A",
    tokensB: "Token B",
  },
  hints: {
    downsampled: "Kurven auf {limit} Punkte reduziert (von {count}).",
  },
  meta: {
    vector: "Vektor",
    letterMass: "Buchstaben-Masse",
    sharedPrimes: "Geteilte Primfaktoren (ggT)",
    ggtKgv: "ggT/kgV",
    tokens: "Token",
    unique: "Unique Wörter",
    topWords: "Top-Wörter",
    vectorBits: "Vektor-Bits",
    primeFactors: "Primfaktoren",
    comparisonHint: "Meta-Vergleich",
  },
  validation: {
    title: "Validierungs-Pipeline (5 Schritte)",
    check: "Prüfung",
    status: "Status",
    empty: "Keine Validierungsdetails.",
    details: "Details",
  },
  pipeline: {
    title: "Validierungs-Pipeline (5 Schritte)",
    step: {
      nfc_tokenization: "NFC-Normalisierung & Token-Parsing",
      bitmask_prefilter: "Bitmasken-Vorfilter (_masks_overlap)",
      geometry_curves: "Geometrische I-Kurven",
      enjambement_phase: "Enjambement-Phasenanalyse",
      meta_profile_audit: "Meta-Profil-Audit",
    },
    status: {
      ok: "ok",
      warn: "Warnung",
      skip: "übersprungen",
    },
    detail: {
      tokenCountA: "Token A",
      tokenCountB: "Token B",
      wordGeometryDtw: "Wort-Geometrie (DTW)",
      wordGeometryMae: "Wort-Geometrie (MAE)",
      literalMatch: "Literal-Match",
      cellGeometry: "Zell-Geometrie",
      substanceGeometry: "Substanz-Geometrie",
      hierarchySentenceDtw: "Satz-Ebene (DTW)",
      hierarchyLineDtw: "Zeilen-Ebene (DTW)",
      metaGgtSimilarity: "Meta-ggT",
      profileOverlap: "Profil-Überlappung",
      sharedPrimeCount: "Geteilte Primfaktoren",
      rhythmBreakCountA: "Rhythmus-Brüche A",
      rhythmBreakCountB: "Rhythmus-Brüche B",
      rhythmBreakDelta: "Δ Brüche",
      phaseShift: "Phasenverschiebung",
      relevant: "Relevant",
      basisOverlap: "Basis-Überlappung",
    },
  },
  axis: {
    title: "Achsen-Fusion (GPM)",
    tokenI: "Token-I-Kurve",
    substance: "Substanz-ggT",
    cellI: "Zell-I",
    hierarchy: "Hierarchie",
    literal: "Literal",
    hierarchySentence: "Satz-Ebene",
    hierarchyLine: "Zeilen-Ebene",
  },
  signals: {
    wordGeometry: "Wort-Geometrie (DTW)",
    fusionScore: "Gesamt-Fusion",
    substanceGgt: "Substanz-ggT (Log)",
    cellLine: "Zelle / Zeile",
    relationTopology: "Relation (Topologie)",
    metaGgt: "Meta-ggT",
    literalByte: "Literal (Byte)",
    substanceParallel: "Substanz-Parallel",
    structuralTwin: "Struktur-Zwilling",
    relationTwins: "Relations-Zwillinge",
    metaGenomeStrong: "Meta-Genom stark",
    wordParallel: "Wort-Parallel",
    keys: {
      word_parallel: "Wort-Parallel",
      relation_twins: "Relations-Zwillinge",
      meta_genome_strong: "Meta-Genom stark",
      substance_parallel: "Substanz-Parallel",
      structural_twin: "Struktur-Zwilling",
    },
  },
  classification: "Klassifikation",
  isomorphismIndex: "Isomorphie-Index",
  interpretation: "Interpretation",
  chains: {
    tokens: "Wort-Token",
    substance: "Substanz-Kette",
    cells: "Arithmetische Zell-Kette (Satz-Ebene)",
    semantic: "Sinn",
    structural: "Raum",
    empty: "Keine Detail-Ketten für diese Ebene.",
    columns: {
      pos: "Pos",
      wordA: "Wort A",
      wordB: "Wort B",
      permIndex: "I",
      siPair: "S(I)",
      iRatio: "i",
      iRatioA: "i A",
      iRatioB: "i B",
      deltaRatio: "Δi",
      deltaIndex: "ΔI",
      sLevel: "S",
      normalized: "Wort",
      substance: "S",
      ggt: "ggT",
      kgv: "kgV",
      ggtKgv: "ggT/kgV",
      sRatio: "s-Ratio",
      cell: "Zelle",
      skeletonA: "Skelett A",
      skeletonB: "Skelett B",
      iSatz: "I_Satz",
      tokenCount: "Token",
      idx: "Idx",
      startA: "start A",
      startB: "start B",
      cntA: "cnt A",
      cntB: "cnt B",
      sA: "S A",
      sB: "S B",
    },
  },
  dtw: {
    label: "DTW-Score",
    failed: "DTW fehlgeschlagen — 0 % ist kein Vergleichswert.",
  },
  enjambement: {
    title: "Rhythmischer Zeilenbruch (Enjambement)",
    detail: "Satz- und Zeilenkanten asynchron.",
    breaks: "Brüche: A: {a} | B: {b} · Δ {delta}",
    profile: "Profil",
    profileSide: "{side}: {value}",
    alignment: "Zeilen-Ausrichtung",
    alignmentSide: "{side}: {value}",
  },
  ingest: {
    sourceLegendA: "Quelle A",
    sourceLegendB: "Quelle B",
    sourceText: "Freitext",
    sourceGpm: ".gpm-Datei",
    dropLabel: ".gpm hier ablegen oder klicken",
    dropEmpty: "Noch keine Datei",
    paste: "Einfügen",
    file: "Datei",
    lockBanner: "Analyse-Modus aktiv. Eingabe eingefroren. Für einen neuen Scan auf „Neuer Vergleich“ klicken.",
    placeholderA: "Plaintext einfügen …",
    placeholderB: "Vergleichstext …",
  },
  spectro: {
    analyze: "Selektion analysieren",
    legend: "Teal Substanz · Amber Struktur · Kreuzfeuer beides",
    empty: "Textbereich in der Matrix markieren, dann analysieren.",
    noDoc: "Kein Dokument — zuerst analysieren.",
    summary: "Treffer",
    crossfire: "Kreuzfeuer",
    tokenRange: "Token {start}–{end} ({count})",
  },
  spectroAnalyze: "Selektion analysieren",
  spectroLegend: "Teal Substanz · Amber Struktur · Kreuzfeuer beides",
  spectroEmpty: "Textbereich in der Matrix markieren, dann analysieren.",
  spectroNoDoc: "Kein Dokument — zuerst analysieren.",
  spectroSummary: "Treffer",
  spectroCrossfire: "Kreuzfeuer",
  empty: "Beide Texte eingeben und analysieren.",
  loading: "Analysiere…",
  disclosure: {
    expandHint: "Aufklappen",
    collapseHint: "Zuklappen",
  },
  hero: {
    title: "Vergleichsergebnis",
    isomorphism: "Isomorphie-Index",
  },
  fusion: {
    word: "Wort-Geometrie",
    substance: "Substanz-Kette",
    cell: "Zell-Geometrie",
    hintDtw: "DTW {score} · Literal {literal}",
    hintAlign: "{align}",
    hintAligned: "Token ausgerichtet",
    hintOffset: "Fenster-Offset {offset}",
    hintSubstance: "{twins} Substanz-Zwillinge · {shadows} Anagramm-Schatten",
    hintSubstanceLen: "Token {lenA}/{lenB} · Ø ggT/kgV {mean}",
    hintCell: "{matches} Skelett-Treffer",
    hintCellLen: "Zellen {lenA}/{lenB}",
    hintDelta: "Δ-Mittel A/B {deltaA}/{deltaB}",
  },
  cards: {
    lens: "Geometrische Linse",
    chains: "Arithmetische Detail-Ketten",
  },
  details: {
    summary: "Experten-Details",
    expertBrief: "{steps} Validierungsschritte · {signals} Signale",
    allSignals: "Alle Signale und Achsen",
    signalsBrief: "{count} Metriken",
    metaGenome: "Meta-Genom A/B",
    metaBrief: "{tokensA}/{tokensB} Token · {uniqueA}/{uniqueB} Wörter",
    vectorTitle: "Vollständiger Meta-Vektor",
    vectorBrief: "Vektor {preview}",
  },
} as const;
