/** Ausgeschriebene Sprachnamen — Codes aus Roman-Alpha-Korpus (OG-Parität). */
export const languages = {
  random: "Random / unsortiert",
  de: "Deutsch",
  en: "Englisch",
  es: "Spanisch",
  fr: "Französisch",
  it: "Italienisch",
  pt: "Portugiesisch",
  ro: "Rumänisch",
  ca: "Katalanisch",
  gl: "Galicisch",
  oc: "Okzitanisch",
  la: "Latein",
  rm: "Rätoromanisch",
  fur: "Friulanisch",
  nl: "Niederländisch",
  da: "Dänisch",
  sv: "Schwedisch",
  nb: "Norwegisch (Bokmål)",
  nn: "Norwegisch (Nynorsk)",
  pl: "Polnisch",
  cs: "Tschechisch",
  sk: "Slowakisch",
  hu: "Ungarisch",
  fi: "Finnisch",
  et: "Estnisch",
  lv: "Lettisch",
  lt: "Litauisch",
  eu: "Baskisch",
  ga: "Irisch",
  gd: "Schottisch-Gälisch",
  cy: "Walisisch",
  br: "Bretonisch",
  is: "Isländisch",
  lb: "Luxemburgisch",
  eo: "Esperanto",
  ia: "Interlingua",
  fy: "Friesisch",
  nds: "Niederdeutsch",
  hr: "Kroatisch",
  sl: "Slowenisch",
  tr: "Türkisch",
  id: "Indonesisch",
  ms: "Malaiisch",
  af: "Afrikaans",
  ast: "Asturisch",
  an: "Aragonesisch",
  bs: "Bosnisch",
  mt: "Maltesisch",
  scn: "Sizilianisch",
  srd: "Sardisch",
  sw: "Suaheli",
  tl: "Tagalog",
  vi: "Vietnamesisch",
  uz: "Usbekisch",
  az: "Aserbaidschanisch",
  ie: "Interlingue",
  mn: "Mongolisch",
} as const;
