export const tensorraum = {
  title: "C(I) Fraktaler Tensorraum",
  lead: "Kanonisieren · speichern · Resonanzmuster vergleichen",
  guide:
    "Quellcode wird in S/N/D/C/H-Pointer übersetzt, in der Registry abgelegt und auf wiederkehrende Strukturen sowie Round-Trip-Reversibilität geprüft.",
  explain: {
    panelTitle: "Erklärung",
    panelBrief: "Tensorraum — Kanonisierung, Registry, Resonanz, Ablage",
    openChapter: "Vollständiges Kapitel in Erklärungen",
  },
  tabs: {
    workspace: "Workspace",
    registry: "Registry",
    redundancy: "Resonanz",
    reversibility: "Round-Trip",
    storage: "Ablage",
    aria: "Tensorraum-Ansichten",
  },
  sidebar: {
    project: "Aktuelles Projekt",
    rename: "Umbenennen",
    newProject: "Neu",
    ingest: "Code einlesen",
    dropHint: "Dateien oder Ordner hierher ziehen",
    filesBtn: "Dateien",
    folderBtn: "Ordner",
    languageFilter: "Sprachfilter",
    toggleAllLanguages: "Alle",
    crossLanguage: "Sprachübergreifend vergleichen",
    structuralOnly: "Nur Struktur (S/N/D/C/H-Typen, ohne konkrete Pointer)",
    windowTitle: "Resonanz-Fenster (Satz)",
    windowFixed: "Fest",
    windowAdaptive: "Adaptiv",
    windowFixedHint: "Gleitfenster für satzübergreifende Resonanz, 50 % Überlappung.",
    windowAdaptiveHint: "Mehrere Fenstergrößen parallel: 8, 12, 16, 20, 24, 28 Token.",
    windowSize: "{count} Token",
    windowAdaptiveRange: "8–28 Token (adaptiv)",
    statFiles: "Dateien",
    statSpaces: "Blöcke",
    statPointers: "Pointer",
    statLanguages: "Sprachen",
    exportRegistry: "Registry exportieren",
    clearProject: "Projekt leeren",
    loadingFiles: "Lade Dateien…",
    projectNamePlaceholder: "Projektname",
  },
  workspace: {
    inputTitle: "Interaktive Eingabe",
    inputSubtitle: "Code-Snippet",
    placeholder:
      "// Quellcode eingeben…\nfunction calculateSum(a, b) {\n    let result = a + b;\n    return result;\n}",
    canonicalize: "Kanonisieren & speichern",
    logTitle: "System-Log",
    logActive: "Aktivität",
    logWaiting: "Warte auf Eingabe…",
  },
  registry: {
    title: "Root Registry (Header)",
    subtitle: "Zentrale Speicherung aller Substanzen · Tabellen und fraktaler Baum",
    headline: "Kanonische Header-Ansicht",
    description: "Substanz-Werte in Tabellen — Pointer-IDs nur als technische Referenz. Fraktal zeigt aufgelöste Sequenzen.",
    views: {
      registry: "Registry",
      tree: "Fraktal",
      aria: "Registry-Ansichten",
    },
    copyPointer: "Pointer-ID kopieren",
    copiedPointer: "Kopiert",
    searchPlaceholder: "Eintrag suchen…",
    sequencePreview: "Sequenz",
    listToolbarLabel: "Registry-Listen",
    listToolbarHint: "Substanz zuerst — gekürzte Pointer-ID rechts (Klick kopiert volle ID).",
    expandAll: "Alle Kategorien aufklappen",
    metrics: {
      files: "Dateien",
      spaces: "Teilräume",
      pointers: "Pointer",
      languages: "Sprachen",
    },
    categories: {
      c: { title: "C(I) Räume & Trenner", subtitle: "Teilräume · Operatoren · Klammern" },
      n: { title: "N(I) Ganzzahlen", subtitle: "Kanonische Ziffernliterale" },
      d: { title: "D(I) Dezimal-Relation", subtitle: "whole · den_reduced · ggt" },
      h: { title: "H(I) Hybrid", subtitle: "S- und N-Segmente in Lesereihenfolge" },
      s: { title: "S(I) Substanzen", subtitle: "Reine Identifier · Strings" },
    },
    canvas: {
      title: "ROOT REGISTRY • CANVAS ATLAS",
      headerStats: "{files} Module · {pointers} Pointer · {languages}/{languageTotal} Sprachen",
      headerFooter: "{entries} Registry-Einträge · aufgeklappt = mehr Kontext",
      hintLeft: "Canvas zeigt die Registry als stabile, breite Strukturkarte.",
      hintRight: "Die Listen rechts bleiben aufklappbar und logisch unverändert.",
      toolbarLabel: "Canvas-Atlas · ROOT-Header",
      toolbarHint: "Große Darstellung für die vier Substanzklassen",
      moreEntries: "+{count} weitere Einträge",
      expanded: "aufgeklappt",
      collapsed: "eingeklappt · per Liste rechts steuerbar",
    },
    expandC: "C aufklappen",
    expandN: "N aufklappen",
    expandD: "D aufklappen",
    expandH: "H aufklappen",
    expandS: "S aufklappen",
    entriesBadge: "{count} Einträge",
    collisionFree: "kollisionsfrei",
    collisions: "{count} Kollisionen",
    emptyCategory: "Leer",
    showAll: "Zeige alle {count} Einträge",
    showLess: "Weniger anzeigen ({count} gesamt)",
    tree: {
      title: "Fraktale Verschachtelung",
      description:
        "Module, Teilräume und Unterblöcke als ausklappbare Strukturkarten — die Tiefe bleibt lesbar.",
      bannerTitle: "Fraktale Verschachtelung",
      bannerHint:
        "Die Baumansicht ist breit angelegt: Module, Teilräume und Unterblöcke werden als Karten dargestellt.",
      metrics: {
        roots: "Wurzelknoten",
        leaves: "Blattknoten",
        maxDepth: "Max. Tiefe",
        view: "Ansicht",
        viewWide: "Breit",
      },
      moduleBadge: "{count} Module",
      moduleLabel: "Modul / Datei",
      spaceLabel: "Teilraum / Block",
      depthLabel: "TIEFE {depth}",
      tokensLabel: "{count} TOKENS",
      childrenLabel: "{count} KINDER",
      sequenceLabel: "{count} Sequenz",
      blocksLabel: "{count} Blöcke",
      noChildren: "Keine weiteren Unterblöcke.",
      noBlocks: "Noch keine verschachtelten Blöcke vorhanden.",
      pathModule: "Modul · {lang}",
      pathSpace: "Blocktiefe {depth} · {id}",
    },
    empty: "Noch keine Registry-Einträge — zuerst Code kanonisieren oder Dateien laden.",
  },
  redundancy: {
    title: "Resonanzmuster",
    lead: "Wiederkehrende kanonische Sequenzen im Projekt — Block- und Satz-Ebene.",
    scan: "Resonanz scannen",
    scanAgain: "Erneut scannen",
    scanParams:
      "Fenster: {window} · Struktur: {structural} · Sprachen: {languages}",
    scanParamsYes: "ja",
    scanParamsNo: "nein",
    scanParamsCross: "übergreifend",
    scanParamsScoped: "pro Sprache",
    subview: {
      block: "Block",
      sentence: "Satz (S(I))",
      aria: "Resonanz-Ebenen",
    },
    emptyNoFiles: "Noch kein kanonisierter Code — zuerst im Workspace speichern oder Dateien laden.",
    emptyNoPatterns: "Kein Resonanzmuster über der Mindestlänge — andere Fenster oder Strukturmodus probieren.",
    emptyNoScan: "Scan starten, um Resonanzmuster im aktuellen Projekt zu finden.",
    card: {
      rank: "#{rank}",
      occurrences: "{count} Vorkommen",
      chainLength: "Länge {count}",
      windowSize: "Fenster {size}",
      locations: "Fundorte",
      locationBlock: "{file} · {nodeId}",
      locationSentence: "{file} · Pos. {start} · Fenster {size}",
      ni: "N(I) ≈ {value}",
      icurve: "I-Kurve",
      signature: "Signatur",
    },
    showMore: "Weitere Muster anzeigen ({count} gesamt)",
    showLess: "Weniger anzeigen",
    scannedAt: "Zuletzt gescannt: {time}",
    resultsCount: "{count} Muster",
    blockLevel: "Block-Ebene",
    sentenceLevel: "Satz-Ebene (S(I))",
    empty: "Keine Redundanzen über Mindestlänge gefunden.",
    chainLength: "Kettenlänge {count}",
    occurrences: "{count} Vorkommen",
    windowSize: "Fenster {size}",
  },
  reversibility: {
    title: "Round-Trip",
    lead: "Jede Datei wird aus der Registry rekonstruiert und mit derselben Tokenizer-Logik erneut geprüft.",
    overviewTitle: "Round-Trip-Beweis",
    overviewHint:
      "Kanonisiertes Original und rekonstruierter Code werden token-für-token verglichen — Abweichungen sind echte Reversibilitätsfehler.",
    empty: "Keine Dateien im Projekt — zuerst kanonisieren.",
    emptyNoFiles: "Noch kein kanonisierter Code — zuerst im Workspace speichern oder Dateien laden.",
    statusOk: "Reversibel",
    statusFail: "Abweichung",
    original: "Original",
    reconstructed: "Rekonstruiert",
    metrics: {
      files: "Dateien",
      passed: "Bestanden",
      maxDepth: "Max. Tiefe",
      visible: "Sichtbar",
    },
    card: {
      linesOriginal: "Original {count} Z.",
      linesReconstructed: "Rekonst. {count} Z.",
      tokens: "{count} Token",
      depth: "Tiefe {depth}",
      failReason: "Grund",
      mismatchAt: "Abweichung bei Token #{index}",
    },
    showMore: "Weitere Dateien anzeigen ({count} gesamt)",
    showLess: "Weniger anzeigen",
  },
  storage: {
    title: "Ablage",
    lead: "Snapshots sichern Rohcode und Einstellungen — Pointer und Registry werden beim Laden neu kanonisiert.",
    compareHint:
      "Snapshot laden erzeugt ein neues Projekt in der Sidebar. Zwischen Projekten wechseln, dann Resonanz oder Round-Trip vergleichen.",
    saveHint: "Nur Rohcode und Einstellungen — keine Pointer-IDs oder Registry.",
    saveCurrent: "Aktuelles Projekt sichern",
    saveSuccess: "Snapshot gespeichert: {name}",
    saveNoFiles: "Keine Dateien zum Sichern — zuerst Code kanonisieren.",
    saveQuotaError: "Browser-Ablage voll — alte Snapshots löschen oder als JSON exportieren.",
    importJson: "JSON importieren",
    importError: "Ungültiges Snapshot-JSON.",
    exportJson: "Als JSON exportieren",
    load: "Als neues Projekt laden",
    loadSuccess: "Geladen als neues Projekt: {name} ({loaded} Dateien, {skipped} übersprungen)",
    delete: "Löschen",
    deleteConfirm: "Snapshot „{name}“ wirklich löschen?",
    empty: "Keine gespeicherten Snapshots.",
    emptyHint: "Im Workspace kanonisieren, dann hier sichern — oder JSON importieren.",
    savedAt: "Gespeichert {date}",
    fromStorageBadge: "Ablage",
    card: {
      files: "{count} Dateien",
      cross: "Sprachübergreifend",
      structural: "Nur Struktur",
      windowFixed: "Fenster {size}",
      windowAdaptive: "Adaptiv 8–28",
    },
  },
  log: {
    skippedIgnored: "Übersprungen: {file} (ignorierter Dateityp)",
    skippedUnknown: "Übersprungen: {file} (unbekannte Erweiterung)",
    skippedLanguage: 'Übersprungen: {file} (Sprache "{lang}" deaktiviert)',
    skippedEmbedded: 'Übersprungen: {file} (eingebettete Sprache "{lang}" deaktiviert)',
    canonicalized: "Kanonisiert: {file} → Sequenzlänge {len}",
    canonicalizeFailed: "Fehler bei {file}: {message}",
    projectCleared: "Projekt geleert.",
    projectCreated: "Projekt erstellt: {name}",
    filesLoaded: "{count} Datei(en) geladen, {skipped} übersprungen, {failed} fehlgeschlagen.",
    exportDone: "Registry exportiert.",
    needOneLanguage: "Mindestens eine Sprache muss aktiv bleiben.",
    savedToStorage: "Snapshot gesichert: {name}",
    loadedFromStorage: "Als neues Projekt geladen: {name} ({loaded} Dateien, {skipped} übersprungen)",
    deletedFromStorage: "Snapshot gelöscht: {name}",
    importedSave: "Snapshot importiert: {name}",
  },
  pointers: {
    S: "Substanz",
    N: "Ganzzahl",
    D: "Dezimal-Relation",
    C: "Räume & Trenner",
    H: "Hybrid",
  },
  common: {
    loading: "Lädt…",
    phase2: "Ansicht wird in Phase 2 vollständig portiert — Kern-Logik läuft bereits im Workspace.",
  },
} as const;
