export const wortpaar = {
  title: "Wortpaar",
  lead: "Zwei Wörter — ggT/kgV (Vergleichen), S_rest (Differenz) oder Anagramm-Suche im Roman-Alpha-Korpus",
  guide:
    "Zwei Wörter eingeben — dann wählst du oben Vergleichen (ggT und kgV), Differenz (S_rest, Teilmenge, Anagramm) oder Anagramm-Suche in der Wort-Datenbank.",
  wordA: "Wort 1",
  wordB: "Wort 2",
  wordAPlaceholder: "Listen",
  wordBPlaceholder: "Silent",
  anagramWord: "Suchwort",
  anagramWordPlaceholder: "Listen",
  submitCompare: "Vergleichen",
  submitDiff: "Differenz berechnen",
  submitAnagram: "Anagramme suchen",
  submit: "Berechnen",
  modes: {
    compare: "Vergleichen",
    diff: "Differenz",
    anagram: "Anagramm",
    compareFull: "Vergleichen (ggT/kgV)",
    diffFull: "Differenz",
  },
  modeAria: "Wortpaar-Modus",
  helpCompareTitle: "Mehr zu Vergleichen",
  helpDiffTitle: "Mehr zur Differenz",
  helpAnagramTitle: "Mehr zur Anagramm-Suche",
  helpCompare:
    "Vergleichen berechnet ggT und kgV der Substanz S beider Wörter sowie die gemeinsamen und einzigartigen Buchstaben.",
  helpDiff:
    "Differenz teilt S durch den ggT: S_rest zeigt, welche Buchstaben übrig bleiben. Anagramm = gleiches S, verschiedenes I.",
  helpAnagram:
    "Ein Wort eingeben — die Datenbank ge_prime_roman_alpha_alt liefert andere Wörter mit gleicher Substanz S, aber anderem Index I (echte Anagramme).",
  resultCompare: "Vergleich",
  resultDiff: "Differenz",
  resultAnagram: "Anagramm-Treffer",
  gcd: "ggT(S₁, S₂)",
  lcm: "kgV(S₁, S₂)",
  gcdHint: "Gemeinsame Primteiler beider Wörter",
  lcmHint: "Kleinste gemeinsame Vielfache der Substanz",
  lcmUnion: "Union aller Buchstaben",
  similarity: "Ähnlichkeit",
  similarityDetail: "ggT ÷ min(S₁, S₂)",
  shared: "Gemeinsam",
  uniqueA: "Nur Wort 1",
  uniqueB: "Nur Wort 2",
  union: "Union",
  restFormula: "S_rest = S₁ ÷ ggT(S₁, S₂)",
  restA: "S_rest (Wort 1)",
  restB: "S_rest (Wort 2)",
  badges: {
    subset12: "Teilmenge von Wort 2",
    subset21: "Teilmenge von Wort 1",
    sameSubstance: "Gleiche Substanz S",
    anagram: "Anagramm",
    identical: "Identisch (S und I)",
    sameLength: "Gleiche Länge",
  },
  anagramHits: "{count} Anagramm(e) gefunden",
  anagramNoHits: "Keine weiteren Anagramme in der Datenbank.",
  anagramTruncated: "Nur die ersten {limit} Treffer angezeigt.",
  anagramDbNote: "Korpus: ge_prime_roman_alpha_alt (Roman-Alpha)",
  anagramDbMissing: "Roman-Alpha-Datenbank nicht gefunden.",
  anagramNotRomanAlpha: "Das Wort enthält Zeichen außerhalb des Roman-Alpha-Zeichensatzes.",
  anagramLanguageGroup: "{language} · {count} Treffer",
  loading: "Berechne…",
  empty: "Wörter eingeben und Modus wählen.",
  tables: {
    original: "Original",
    normalized: "Normalisiert",
    language: "Sprache",
    index: "Index I",
  },
} as const;
