import type { LanguageConfig } from "./types";

export const BIG_PRIME = 100000000000000003n;

export const PRIME_ALPHABET: Record<string, bigint> = {
  E: 2n,
  A: 3n,
  O: 5n,
  I: 7n,
  T: 11n,
  N: 13n,
  R: 17n,
  S: 19n,
  L: 23n,
  C: 29n,
  D: 31n,
  U: 37n,
  M: 41n,
  P: 43n,
  H: 47n,
  G: 53n,
  B: 59n,
  F: 61n,
  Y: 67n,
  W: 71n,
  K: 73n,
  V: 79n,
  X: 83n,
  Z: 89n,
  J: 97n,
  Q: 101n,
  "ẞ": 103n,
};

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  { id: "js", name: "JavaScript/TS", ext: [".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs"], blockStyle: "brace", commentStyle: "c" },
  { id: "py", name: "Python", ext: [".py", ".pyw", ".pyi"], blockStyle: "indent", commentStyle: "hash" },
  { id: "c", name: "C/C++", ext: [".c", ".cpp", ".h", ".hpp", ".cc", ".cxx"], blockStyle: "brace", commentStyle: "c" },
  { id: "java", name: "Java", ext: [".java"], blockStyle: "brace", commentStyle: "c" },
  { id: "go", name: "Go", ext: [".go"], blockStyle: "brace", commentStyle: "c" },
  { id: "rs", name: "Rust", ext: [".rs"], blockStyle: "brace", commentStyle: "c" },
  { id: "php", name: "PHP", ext: [".php", ".php3", ".php4", ".php5", ".phtml"], blockStyle: "brace", commentStyle: "c" },
  {
    id: "rb",
    name: "Ruby",
    ext: [".rb", ".rbw"],
    blockStyle: "keyword",
    commentStyle: "hash",
    blockPairs: [
      { open: "DO", close: "END" },
      { open: "DEF", close: "END" },
      { open: "CLASS", close: "END" },
      { open: "MODULE", close: "END" },
      { open: "BEGIN", close: "END" },
    ],
  },
  { id: "cs", name: "C#", ext: [".cs"], blockStyle: "brace", commentStyle: "c" },
  { id: "swift", name: "Swift", ext: [".swift"], blockStyle: "brace", commentStyle: "c" },
  { id: "kt", name: "Kotlin", ext: [".kt", ".kts"], blockStyle: "brace", commentStyle: "c" },
  { id: "html", name: "HTML", ext: [".html", ".htm", ".xhtml"], blockStyle: "tag", commentStyle: "none" },
  { id: "css", name: "CSS", ext: [".css", ".scss", ".sass", ".less"], blockStyle: "brace", commentStyle: "c" },
  {
    id: "sql",
    name: "SQL",
    ext: [".sql"],
    blockStyle: "keyword",
    commentStyle: "sql",
    blockPairs: [
      { open: "BEGIN", close: "END" },
      { open: "CASE", close: "END" },
    ],
  },
  {
    id: "sh",
    name: "Shell",
    ext: [".sh", ".bash", ".zsh", ".fish"],
    blockStyle: "keyword",
    commentStyle: "hash",
    blockPairs: [
      { open: "IF", close: "FI" },
      { open: "FOR", close: "DONE" },
      { open: "WHILE", close: "DONE" },
      { open: "UNTIL", close: "DONE" },
      { open: "CASE", close: "ESAC" },
    ],
  },
  { id: "xml", name: "XML", ext: [".xml", ".xsd", ".xslt", ".svg"], blockStyle: "tag", commentStyle: "none" },
  { id: "json", name: "JSON", ext: [".json", ".jsonl"], blockStyle: "brace", commentStyle: "c" },
  { id: "yaml", name: "YAML", ext: [".yml", ".yaml"], blockStyle: "indent", commentStyle: "hash" },
  { id: "toml", name: "TOML", ext: [".toml"], blockStyle: "flat", commentStyle: "hash" },
  { id: "markdown", name: "Markdown", ext: [".md", ".markdown"], blockStyle: "flat", commentStyle: "none" },
];

export const IGNORED_SUFFIXES = [
  ".min.js",
  ".min.css",
  ".zip",
  ".rar",
  ".7z",
  ".tar",
  ".gz",
  ".bz2",
  ".xz",
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".bmp",
  ".webp",
  ".ico",
  ".mp3",
  ".mp4",
  ".wav",
  ".flac",
  ".ogg",
  ".webm",
  ".exe",
  ".dll",
  ".so",
  ".dylib",
  ".bin",
  ".out",
  ".pdf",
  ".doc",
  ".docx",
  ".xls",
  ".xlsx",
  ".ppt",
  ".pptx",
  ".ttf",
  ".otf",
  ".woff",
  ".woff2",
  ".pyc",
  ".pyo",
  ".class",
  ".jar",
  ".db",
  ".sqlite",
  ".sqlite3",
  ".log",
  ".tmp",
  ".temp",
];

export const ADAPTIVE_WINDOW_SIZES = [8, 12, 16, 20, 24, 28] as const;
export const MIN_CHAIN_LENGTH = 8;
export const DEFAULT_WINDOW_SIZE = 15;

export const TOKENIZER_REGEX =
  /("(?:\\[\s\S]|[^"\\])*"|'(?:\\[\s\S]|[^'\\])*'|`(?:\\[\s\S]|[^`\\])*`|\b(?:FUNCTION|CLASS|IF|ELSE|FOR|WHILE|DO|SWITCH|RETURN|IMPORT|EXPORT|LET|VAR|CONST|NEW)\b|\b[A-Z_][\w\u1E9E]*\b|[0-9]+\.[0-9]+|[0-9]+|[\{\}\(\)\[\]]|[+\-*\/=<>!&|%^~?:]+|[.,;])/g;

export const TAG_REGEX =
  /<!--[\s\S]*?-->|<\/([A-Za-z_][\w:.\-]*)\s*>|<([A-Za-z_][\w:.\-]*)((?:\s+[^<>]*?)?)\s*(\/?)>|[^<]+/g;

export const VOID_HTML_TAGS = new Set([
  "BR",
  "IMG",
  "INPUT",
  "HR",
  "META",
  "LINK",
  "AREA",
  "BASE",
  "COL",
  "EMBED",
  "SOURCE",
  "TRACK",
  "WBR",
]);
